### ISSUE TITLE
Fundamento JavaScript I-Punto 9- Preparación.

### ISSUE THREAD

**Issue by USERcndv2021** [USERcndv2021/practica_dwec_gestor_presupuesto#1]
Hola @pedroprieto,
He ejecutado el comando **npm install** para instalar las librerías de Node, (se genera la carpeta node_modules en el repositorio) pero dicha ejecución requería lanzar el comando **npm audit fix** para identificar y solucionar problemas con su instalación. Al lanzar dicho comando compruebo con git status que hay algún tipo de modificación en el **archivo package-lock.json**.
Duda:
1- ¿Creo un nuevo commit para integrar los cambios existentes en el archivo **package-lock.json** al repositorio de GitHub antes de hacer el test?, ¿provocaría algún tipo de conflicto dicho cambio?.

Un saludo,
Muchas gracias.

**Comment by pedroprieto** [comment]
Buenas,

Puedes integrar los cambios en `package-lock.json` sin problema. Lo de la auditoría es porque hay alguna versión antigua. No hay problema. Puedes ejecutarlo o no, como prefieras.

Un saludo!!
