### ISSUE TITLE
Fundamentos JavaScript I - No pasa test la función actualizarValor.

### ISSUE THREAD

**Issue by USERcndv2021** [USERcndv2021/practica_dwec_gestor_presupuesto#2]
Hola @pedroprieto,
Podrías echarle un vistazo a la función **actualizarValor** de JavaScrip I, no consigo que pase el test..

Muchas gracias,

Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

Este código es raro:
https://github.com/USERcndv2021/practica_dwec_gestor_presupuesto/blob/a52f461f19e076a3f0eda79fd0e89304cca45f8c/js/gestionPresupuesto.js#L36-L38

Supongo que querrás:
```js
this.valor = nuevoValor < 0 || isNaN(this.nuevoValor) ? this.valor: this.nuevoValor; 
```

Un saludo!
